In [1]:
import cv2
import pickle
import numpy as np
import os

In [ ]:
name=input("Enter your name:")
Entry_number = input("Enter your entry number:")
Email= input("Enter your email:")
Department= input("Enter your department:")

In [ ]:
video=cv2.VideoCapture(0)
facedetect=cv2.CascadeClassifier('data/haarcascade_frontalface_default.xml')
faces_data=[]
i=0

while True:
    ret,frame=video.read()
    gray=cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces=facedetect.detectMultiScale(gray, 1.3 ,5)
    for (x,y,w,h) in faces:
        crop_img=frame[y:y+h, x:x+w, :]
        resized_img=cv2.resize(crop_img, (50,50))
        if len(faces_data)<=50 and i%10==0:
            faces_data.append(resized_img)
        i=i+1
        
        cv2.putText(frame, str(len(faces_data)), (50,50), cv2.FONT_HERSHEY_COMPLEX, 1, (0,0,255), 1)
        
        cv2.rectangle(frame, (x,y), (x+w, y+h), (0,0,255), 1)
        
    cv2.imshow("Frame",frame)
    k=cv2.waitKey(1)
    if k==ord('q') or len(faces_data)==50:
        break
video.release()
cv2.destroyAllWindows()

faces_data=np.asarray(faces_data)
faces_data=faces_data.reshape(50, -1)

In [2]:
if 'names.pkl' not in os.listdir('data/'):
    names=[name]*50
    with open('data/names.pkl', 'wb') as f:
        pickle.dump(names, f)
else:
    with open('data/names.pkl', 'rb') as f:
        names=pickle.load(f)
    names=names+[name]*50
    with open('data/names.pkl', 'wb') as f:
        pickle.dump(names, f)

if 'faces_data.pkl' not in os.listdir('data/'):
    with open('data/faces_data.pkl', 'wb') as f:
        pickle.dump(faces_data, f)
else:
    with open('data/faces_data.pkl', 'rb') as f:
        faces=pickle.load(f)
    faces=np.append(faces, faces_data, axis=0)
    with open('data/faces_data.pkl', 'wb') as f:
        pickle.dump(faces, f)

if 'Emails.pkl' not in os.listdir('data/'):
    Emails=[Email]*50
    with open('data/Emails.pkl', 'wb') as f:
        pickle.dump(Emails, f)
else:
    with open('data/Emails.pkl', 'rb') as f:
        Emails=pickle.load(f)
    Emails=Emails+[Email]*50
    with open('data/Emails.pkl', 'wb') as f:
        pickle.dump(Emails, f)
        

if 'Departments.pkl' not in os.listdir('data/'):
    Departments=[Department]*50
    with open('data/Departments.pkl', 'wb') as f:
        pickle.dump(Departments, f)
else:
    with open('data/Departments.pkl', 'rb') as f:
        Departments=pickle.load(f)
    Departments=Departments+[Department]*50
    with open('data/Departments.pkl', 'wb') as f:
        pickle.dump(Departments, f)


if 'Entry_numbers.pkl' not in os.listdir('data/'):
    Entry_numbers=[Entry_number]*50
    with open('data/Entry_numbers.pkl', 'wb') as f:
        pickle.dump(Entry_numbers, f)
else:
    with open('data/Entry_numbers.pkl', 'rb') as f:
        Entry_numbers=pickle.load(f)
    Entry_numbers=Entry_numbers+[Entry_number]*50
    with open('data/Entry_numbers.pkl', 'wb') as f:
        pickle.dump(Entry_numbers, f)

NameError: name 'name' is not defined

In [3]:
import pickle
with open('data/Emails.pkl', 'rb') as f:
    EMAILS = pickle.load(f)
    print(EMAILS)

['infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmail.com ', 'infoamrit2004@gmai

In [4]:
with open('data/names.pkl', 'rb') as f:
    NAMES =pickle.load(f) 
    print(NAMES)

['Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush', 'Piyush']


In [5]:
with open('data/Entry_numbers.pkl', 'rb') as w:
    Entry_number =pickle.load(w)
    print(Entry_number)

['23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061', '23bcs061']


In [6]:
with open('data/faces_data.pkl', 'rb') as f:
    FACES=pickle.load(f)
    print(FACES)

[[ 47  43  43 ...  19  22  23]
 [131 133 151 ...  62  71  93]
 [ 31  23  30 ...  38  39  49]
 ...
 [ 36  41  46 ...  62  71  98]
 [ 73  74  83 ...  88  99 132]
 [134 140 147 ...  90 102 134]]
